In [1]:
from intrepid_environment.quadcopter_environment import QuadcopterController

In [2]:
import nest_asyncio
nest_asyncio.apply()

In [3]:
# Simulation frequency
DT_MS = 100
quadcopter_controller = QuadcopterController(DT_MS)

Read quadcopter sensors.

In [4]:
quadcopter_controller.position()

array([0., 0., 0.])

In [5]:
quadcopter_controller.linear_velocity()

array([-0., -0.,  0.])

In [6]:
quadcopter_controller.acceleration()

array([-0., -0.,  0.])

In [7]:
quadcopter_controller.rotation_angles()

array([-0., -0.,  0.])

In [8]:
quadcopter_controller.angular_velocity()

array([-0., -0.,  0.])

Send motor commands.

In [9]:
quadcopter_controller.control_motors(0.4, 0.7, 0.1, 0.33)

Control with random motor commands for 1000 timesteps (10 sec)

In [10]:
import numpy as np


for _ in range(0, 1000):
  thrust = np.random.uniform(0, 100, 4).tolist()
  try:
    quadcopter_controller.control_motors(*thrust)
    quadcopter_controller.step()
  except Exception as e:
    print("drone crashed")
    break

drone crashed
